LIB_DB = 'data/ihaveread.db'

KEY_SEARCH_BOOK = "-SEARCH_BOOK-"
KEY_SEARCH_AUTHOR = "-SEARCH_AUTHOR-"
KEY_RESULTS = "-RESULTS-"
KEY_BOOK_LIST_SIZE = "-BOOK_LIST_SIZE-"

KEY_AUTHOR_LIST = "-AUTHOR_LIST-"
KEY_BOOK_LIST = "-BOOK_LIST-"

KEY_AUTHOR_NAME = "-KEY_AUTHOR_NAME-"
KEY_AUTHOR_SURNAME = "-KEY_AUTHOR_SURNAME-"
KEY_AUTHOR_LANG = "-KEY_AUTHOR_LANG-"
KEY_AUTHOR_SYNONYMS = "-KEY_AUTHOR_SYNONYMS-"
KEY_AUTHOR_SYN_NAME = "-KEY_AUTHOR_SYN_NAME-"
KEY_AUTHOR_SYN_LANG = "-KEY_AUTHOR_SYN_LANG-"
KEY_AUTHOR_SYN_TYPE = "-KEY_AUTHOR_SYN_TYPE-"

KEY_BOOK_TITLE = "-KEY_BOOK_TITLE-"
KEY_BOOK_LANG = "-KEY_BOOK_LANG-"
KEY_ORIG_BOOK_TITLE = "-KEY_ORIG_BOOK_TITLE-"
KEY_ORIG_BOOK_LANG = "-KEY_ORIG_BOOK_LANG-"
KEY_READ_BOOK_LANG = "-KEY_READ_BOOK_LANG-"
KEY_BOOK_PUBL_DATE = "-KEY_BOOK_PUBL_DATE-"
KEY_BOOK_READ_DATE = "-KEY_BOOK_READ_DATE-"
KEY_BOOK_GENRE = "-KEY_BOOK_GENRE-"
KEY_BOOK_NOTE = "-KEY_BOOK_NOTE-"
KEY_BOOK_AUTHORS = "-KEY_BOOK_AUTHORS-"
KEY_BOOK_MEDIUM = "-KEY_BOOK_MEDIUM-"
KEY_BOOK_SCORE = "-KEY_BOOK_SCORE-"
KEY_BOOK_TRANSLATIONS = "-KEY_BOOK_TRANSLATIONS-"

KEY_ALT_BOOK_TITLE = "-KEY_ALT_BOOK_TITLE-"
KEY_ALT_BOOK_LANG = "-KEY_ALT_BOOK_LANG-"

def ifnull(var, val):
    if var is None:
        return val
    return var
